name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build + Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
    - name: Build
      run: go build .
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
    - name: Run actionlint
      uses: raven-actions/actionlint@v2

  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run actionlint
      uses: raven-actions/actionlint@v2
